import { Shirt, Footprints, Truck, ArrowUpRight } from 'lucide-react';
import { cn } from '@/lib/utils';

const pillars = [
  {
    icon: Shirt,
    title: 'Fashion',
    subtitle: 'Design & Lifestyle',
    description: 'The creative engine of the ecosystem. This pillar bridges high-end design with digital scarcity, offering exclusive apparel and collections that provide direct utility and status to Sentinel holders within the ecosystem.',
    gradient: 'from-violet-500/10 to-primary/10',
    url: 'https://underva.com/',
  },
  {
    icon: Footprints,
    title: 'Stride',
    subtitle: 'Sportswear & Performance',
    description: 'The performance engine. Focused on athletic gear and performance-based initiatives, this pillar facilitates the intersection of physical endurance and digital reward mechanics, where active engagement in sport is recognized and incentivized through the tokenomics.',
    gradient: 'from-primary/10 to-cyan-500/10',
    url: 'https://undervastride.com/',
  },
  {
    icon: Truck,
    title: 'Express',
    subtitle: 'Logistics & Supply Chain',
    description: 'The infrastructure backbone. Express handles the complex, real-world movement of goods generated by the Fashion and Stride pillars. It ensures that the digital-to-physical bridge is seamless, utilizing transparent logistics tracking that allows the ecosystem to scale commercial operations while maintaining the integrity of every physical delivery.',
    gradient: 'from-cyan-500/10 to-emerald-500/10',
    url: 'https://undervaexpress.com/',
  },
];

export function DocThreePillars() {
  return (
    <div className="space-y-8">
      <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
        Our industrial foundation is built upon three specific pillars that drive the ecosystem's economic cycle:
      </p>

      <div className="grid gap-4">
        {pillars.map((pillar) => (
          <div
            key={pillar.title}
            className={cn(
              "relative rounded-xl border border-primary/10 bg-card p-6 overflow-hidden group",
              "hover:border-primary/20 transition-colors"
            )}
          >
            <div className={cn("absolute inset-0 opacity-50 bg-gradient-to-br", pillar.gradient)} />
            <div className="relative z-10">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <pillar.icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-semibold text-foreground">{pillar.title}</h3>
                    <p className="text-xs text-primary font-medium">{pillar.subtitle}</p>
                  </div>
                </div>
                <a
                  href={pillar.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1 text-xs text-primary hover:underline"
                >
                  Visit <ArrowUpRight className="h-3 w-3" />
                </a>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">{pillar.description}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
