import { Wallet, Shield, Coins, Vote } from 'lucide-react';

const utilities = [
  {
    icon: Wallet,
    title: 'Ecosystem Payment Rail',
    description: '$WOU is the primary currency for all transactions across the industrial pillars. Whether purchasing apparel from Fashion, performance gear from Stride, or logistics services from Express, $WOU serves as the standard medium of exchange.',
  },
  {
    icon: Shield,
    title: 'Access & Credentialing',
    description: 'While the Sentinel NFT acts as the "Bearer Instrument" for status and rights, $WOU is required to maintain active participation in the various loyalty and reward tiers associated with those credentials.',
  },
  {
    icon: Coins,
    title: 'Cashback & Reward Engine',
    description: 'All cashback rebates (2.0% standard, 5.0% Origin tier) are denominated and distributed in $WOU. This ensures that rewards generated by commercial activity are recirculated within the ecosystem, further driving the utility cycle.',
  },
  {
    icon: Vote,
    title: 'Governance Participation',
    description: 'Holding and using $WOU, alongside Sentinel credentials, gives participants the standing needed to engage in the strategic coordination managed by the Sentinel Assembly.',
  },
];

export function DocTokenUtility() {
  return (
    <div className="space-y-8">
      <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
        The utility of the <span className="font-mono text-foreground font-semibold">$WOU</span> token is derived 
        from its role in facilitating ecosystem wide interactions:
      </p>

      <div className="grid gap-4">
        {utilities.map((item, index) => (
          <div key={item.title} className="flex items-start gap-4 rounded-xl border border-primary/10 bg-card p-5">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <item.icon className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-foreground mb-1.5">{item.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
